image: java:8-jdk

stages:
  - build

job_build:
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
    - spring-boot-demo/build/libs/*.jar
  only:
    - master
  tags:
    - java
    - docker